services:
  main:
    build:
      context: ./amin
      dockerfile: ./docker/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      APP_DISCORD_TOKEN: ${APP_DISCORD_TOKEN}
      DEFAULT_JOIN_SUFFIX: ${DEFAULT_JOIN_SUFFIX}
      DEFAULT_LEAVE_SUFFIX: ${DEFAULT_LEAVE_SUFFIX}
      DEFAULT_VOICE_MODEL: ${DEFAULT_VOICE_MODEL}
      TTS_REGION: ${TTS_REGION}
      TTS_APIKEY: ${TTS_APIKEY}
      ADMINS: ${ADMINS}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  dashboard:
    build:
      context: ./dashboard
      dockerfile: ./docker/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      DEFAULT_JOIN_SUFFIX: ${DEFAULT_JOIN_SUFFIX}
      DEFAULT_LEAVE_SUFFIX: ${DEFAULT_LEAVE_SUFFIX}
      DEFAULT_VOICE_MODEL: ${DEFAULT_VOICE_MODEL}
      TTS_REGION: ${TTS_REGION}
      TTS_APIKEY: ${TTS_APIKEY}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      ADMINS: ${ADMINS}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./proto/v1/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: