// Stable error codes for every error a client can receive from a server function.
// Handlers compose `Result<V, ErrorCode>` (see #/server/middlware's resultHandler)
// instead of throwing, so the client can branch on a code instead of parsing message strings.

export const ErrorCode = {
    // OAuth2 / authorization (src/server/authorization)
    AUTH_STATE_COOKIE_SET_FAILED: "AUTH_STATE_COOKIE_SET_FAILED",
    AUTH_STATE_COOKIE_MISSING: "AUTH_STATE_COOKIE_MISSING",
    AUTH_STATE_COOKIE_READ_FAILED: "AUTH_STATE_COOKIE_READ_FAILED",
    AUTH_STATE_MISMATCH: "AUTH_STATE_MISMATCH",
    AUTH_TOKEN_EXCHANGE_FAILED: "AUTH_TOKEN_EXCHANGE_FAILED",
    AUTH_USER_FETCH_FAILED: "AUTH_USER_FETCH_FAILED",
    AUTH_LOGOUT_FAILED: "AUTH_LOGOUT_FAILED",

    // Session lifecycle (src/server/sessions, src/services/sessions)
    SESSION_COOKIE_SET_FAILED: "SESSION_COOKIE_SET_FAILED",
    SESSION_COOKIE_MISSING: "SESSION_COOKIE_MISSING",
    SESSION_COOKIE_READ_FAILED: "SESSION_COOKIE_READ_FAILED",
    SESSION_COOKIE_DELETE_FAILED: "SESSION_COOKIE_DELETE_FAILED",
    SESSION_CREATE_FAILED: "SESSION_CREATE_FAILED",
    SESSION_STORE_READ_FAILED: "SESSION_STORE_READ_FAILED",
    SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
    SESSION_EXPIRED: "SESSION_EXPIRED",
    SESSION_UPDATE_FAILED: "SESSION_UPDATE_FAILED",
    SESSION_DELETE_FAILED: "SESSION_DELETE_FAILED",

    // Profile / app config / permissions (src/server/profile)
    PROFILE_GUILD_NOT_JOINED: "PROFILE_GUILD_NOT_JOINED",
    PROFILE_ADMIN_REQUIRED: "PROFILE_ADMIN_REQUIRED",
    PROFILE_SESSION_UPDATE_FAILED: "PROFILE_SESSION_UPDATE_FAILED",
    PROFILE_SPEECH_NOTICE_FETCH_FAILED: "PROFILE_SPEECH_NOTICE_FETCH_FAILED",
    PROFILE_SPEECH_NOTICE_UPDATE_FAILED: "PROFILE_SPEECH_NOTICE_UPDATE_FAILED",
    PROFILE_APP_CONFIG_UPDATE_FAILED: "PROFILE_APP_CONFIG_UPDATE_FAILED",
    PROFILE_GUILD_MEMBER_FETCH_FAILED: "PROFILE_GUILD_MEMBER_FETCH_FAILED",

    // TTS (src/server/tts, src/services/microsoft-tts)
    TTS_NO_GUILD_ACCESS: "TTS_NO_GUILD_ACCESS",
    TTS_TOKEN_ISSUE_FAILED: "TTS_TOKEN_ISSUE_FAILED",

    // Upstream Discord API (src/services/oauth2-provider)
    DISCORD_API_ERROR: "DISCORD_API_ERROR",
    DISCORD_OAUTH_TOKEN_EXCHANGE_FAILED: "DISCORD_OAUTH_TOKEN_EXCHANGE_FAILED",
    DISCORD_OAUTH_REFRESH_FAILED: "DISCORD_OAUTH_REFRESH_FAILED",
    DISCORD_OAUTH_REVOKE_FAILED: "DISCORD_OAUTH_REVOKE_FAILED",
    DISCORD_NO_REFRESH_TOKEN: "DISCORD_NO_REFRESH_TOKEN",

    // Database (src/services/database)
    DATABASE_NOT_FOUND: "DATABASE_NOT_FOUND",
    DATABASE_INVALID_ID: "DATABASE_INVALID_ID",
    DATABASE_QUERY_FAILED: "DATABASE_QUERY_FAILED",

    // Cache (src/services/cache)
    CACHE_OPERATION_FAILED: "CACHE_OPERATION_FAILED",

    // Cross-cutting
    VALIDATION_FAILED: "VALIDATION_FAILED",
    INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
